CREATE TABLE IF NOT EXISTS surveys (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR NOT NULL,
  description TEXT
);

CREATE TABLE IF NOT EXISTS questions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  survey_id INTEGER NOT NULL,
  type INTEGER NOT NULL,
  question VARCHAR NOT NULL,
  body_text TEXT,
  img_url VARCHAR,
  max_options INTEGER NOT NULL DEFAULT 1,
  FOREIGN KEY (survey_id) REFERENCES surveys(id)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS questions_options (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  question_id INTEGER NOT NULL,
  number INTEGER NOT NULL,
  text_value VARCHAR NOT NULL,
  img_url VARCHAR,
  is_alternative BOOLEAN NOT NULL DEFAULT 0,
  FOREIGN KEY (question_id) REFERENCES questions(id)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS submitted (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  date VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS submitted_answer (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  submitted_id INTEGER NOT NULL,
  question_id INTEGER NOT NULL,
  json_answer TEXT NOT NULL,
  FOREIGN KEY (submitted_id) REFERENCES submitted(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (question_id) REFERENCES questions(id)
    ON UPDATE CASCADE ON DELETE NO ACTION
);
